WebStore/Models/Cart.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace WebStore.Models
{
    public class Cart
    {
        private List<CartLine> cartLines = new List<CartLine>();

        public void AddItem(ProductModel product, int quantity)
        {
            if(quantity<0)
            {
                RemoveItem(product, -quantity);
                return;
            }
            CartLine line = cartLines
                .Where(p => p.Product.ProductId == product.ProductId)
                .FirstOrDefault();
            if (line == null)
                cartLines.Add(new CartLine { Product = product, Quantity = quantity, ProductId = product.ProductId });
            else
                line.Quantity += quantity;
        }

        public void RemoveItem(ProductModel product, int quantity)
        {
            CartLine line = cartLines
                .Where(p => p.Product.ProductId == product.ProductId)
                .FirstOrDefault();
            if (line != null)
            {
                if (line.Quantity-quantity >= 1)
                    line.Quantity -= quantity;
                else
                    cartLines.Remove(line);
            }
        }

        public int GetTotalItems()
        {
            int qnt = 0;
            foreach(CartLine line in cartLines)
            {
                qnt += line.Quantity;
            }
            return qnt;
        }

        public void RemoveLine(ProductModel product)
        {
            cartLines.RemoveAll(p => p.Product.ProductId == product.ProductId);
        }

        public double TotalValue()
        {
            return cartLines.Sum(p => p.Product.Price * p.Quantity);
        }

        public void Clear()
        {
            cartLines.Clear();
        }

        public IEnumerable<CartLine> Lines
        {
            get { return cartLines; }
        }
    }

    public class CartLine
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public int ProductId { get; set; }
        public virtual ProductModel Product { get; set; }
        public int Quantity { get; set; }
        public int PurchaseId { get; set; }
        public Purchase Purchase { get; set; }
    }
}

WebStore/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebStore.Models;

namespace WebStore.Controllers
{
    public class CartController : Controller
    {
        // GET: Cart
        // List of current items in cart
        public ActionResult Index()
        {
            Cart cart = GetCart();
            return View(cart);
        }

        // Current cart state (Total items and total value)
        public JsonResult State()
        {
            Cart cart = GetCart();
            return Json(new { count = cart.GetTotalItems(), value = cart.TotalValue().ToString("c") }, JsonRequestBehavior.AllowGet);
        }

        // Adding or removing an item to cart
        [HttpPost]
        public JsonResult UpdateCart(int id, int quantity)
        {
            using(ApplicationDbContext db = new ApplicationDbContext())
            {
                var product = db.Products.Find(id);
                if(product!=null)
                {
                    var currentLine = GetCart().Lines.Where(p => p.Product.ProductId == product.ProductId).FirstOrDefault();
                    int qnt = 1;
                    int totalQnt = 1;
                    if (currentLine != null)
                    {
                        qnt = quantity - currentLine.Quantity;
                        totalQnt = (currentLine.Quantity + qnt);
                    }
                    GetCart().AddItem(product, qnt);
                    return Json(new { price = (totalQnt * product.Price).ToString("c") });
                }
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(new { message = "Error! There is no such item in store" });
            }
        }

        // Removing line from cart
        public ActionResult RemoveLineFromCart(int id)
        {
            using (ApplicationDbContext db = new ApplicationDbContext())
            {
                var product = db.Products.Find(id);
                if (product != null)
                {
                    GetCart().RemoveLine(product);
                    return PartialView("_PartialCart", GetCart());
                }
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(new { message = "Error! There is no such item in store" });
            }
        }
        
        private Cart GetCart()
        {
            Cart cart = (Cart)Session["Cart"];
            if (cart == null)
            {
                cart = new Cart();
                Session["Cart"] = cart;
            }
            return cart;
        }
    }
}

WebStore/Controllers/PurchaseController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebStore.Models;

namespace WebStore.Controllers
{
    public class PurchaseController : Controller
    {
        // GET: Purchase
        // List of user's purchases
        [Authorize]
        public ActionResult Index()
        {
            using (ApplicationDbContext db = new ApplicationDbContext())
            {
                var userId = System.Web.HttpContext.Current.User.Identity.GetUserId();
                var purchases = db.Purchases.Include("Items").Include("Items.Product").OrderByDescending(x => x.PurchaseTime).ToList();
                return View(purchases);
            }
        }


        // GET
        // Adding a new purchase
        [Authorize]
        public ActionResult Add()
        {
            Cart cart = GetCart();
            if (cart != null)
            {
                using (ApplicationDbContext db = new ApplicationDbContext())
                {
                    var user = db.Users.Find(System.Web.HttpContext.Current.User.Identity.GetUserId());
                    var userId = System.Web.HttpContext.Current.User.Identity.GetUserId();
                    Purchase purchase = new Purchase
                    {
                        PurchaseTime = DateTime.Now,
                        ApplicationUser = user,
                        ApplicationUserId = userId,
                        TotalValue = cart.TotalValue()
                    };
                    for (int i = 0; i < cart.Lines.Count(); i++)
                    {
                        // Changing in-stock quantity
                        var product = db.Products.Find(cart.Lines.ElementAt(i).Product.ProductId);
                        product.CountInStore -= cart.Lines.ElementAt(i).Quantity;
                        db.Entry(product).State = System.Data.Entity.EntityState.Modified;

                        // Adding products to a new purchase
                        cart.Lines.ElementAt(i).Product = null;
                        cart.Lines.ElementAt(i).PurchaseId = purchase.Id;
                        db.CartLines.Add(cart.Lines.ElementAt(i));
                    }
                    db.Purchases.Add(purchase);
                    db.SaveChanges();
                }
                Session["Cart"] = new Cart();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index", "Cart");
        }

        public Cart GetCart()
        {
            Cart cart = (Cart)Session["Cart"];
            return cart;
        }
    }
}

WebStore/Views/Cart/Index.cshtml
@using WebStore.Models
@model Cart

@{
    ViewBag.Title = "Корзина";
}
    <h1>Корзина</h1>
    <div align="center" class="cart-body">
        @Html.Partial("_PartialCart")
    </div>
    <div class="cart-final">
        <span class="final-title">Ваша корзина</span>
        <p>
            Количество товаров:
            <span class="item-count">@Model.GetTotalItems()</span>
        </p>
        <p>
            Общая стоимость:
            <span class="item-value">@Model.TotalValue().ToString("c");</span>
        </p>
        <button onclick="buyHandler()" class="btn-lg btn-success">Купить</button>
    </div>
</div>

<script>
    function buyHandler() {
        window.location.href = '@Url.Action("Add","Purchase")';
    }

    function changeQnt(id) {
        setTimeout(toCart(id), 2000);
    }

    async function deleteLineHandler(id) {
        let url = '@Url.Action("RemoveLineFromCart","Cart")/' + id;
        let response = await fetch(url, {
            method: 'POST'
        });
        let result = await response.text();
        if (response.ok) {
            changeItems(result);
            await getState();
        }
    }

    function changeItems(html){
        var mainDiv = document.getElementsByClassName("cart-body")[0];
        mainDiv.innerHTML = html;
    }

    function checkBorders(item) {
        if (item.value < 1)
            item.value = 1;
        if (+item.value > +item.getAttribute('max'))
            item.value = item.getAttribute('max');
    }

    async function toCart(id) {
        let url = '@Url.Action("UpdateCart", "Cart")?id=' + id + '&quantity=';
        let item = document.getElementById(id).getElementsByTagName("input")[0];
        let price = document.getElementById(id).getElementsByClassName("price")[0];
        checkBorders(item);
        url = url + item.value;
        let response = await fetch(url, {
            method: 'POST'
        })
        let result = await response.json();
        if (response.ok) {
            getState();
            price.innerHTML = result.price;
        }
        else
            alert(result.message);
    }

    function deleteProducts() {


    }
</script>

WebStore/Views/Cart/_PartialCart.cshtml
@using WebStore.Models
@using System;
@using System.Collections.Generic;
@using System.Linq;
@using System.Net;
@using System.Web;

@model Cart

@foreach (CartLine line in Model.Lines)
{
    <div id="@line.Product.ProductId" class="cart-product @if (Model.Lines.Last()==line) {<text>cart-product-last-child</text>}">
        <img src="@Url.Action("Image", "Product", new { id = line.Product.ProductId })" />
        <span class="name">@line.Product.Name</span>
        <span class="price">@((line.Product.Price * line.Quantity).ToString("c"));</span>
        <input type="number" min="1" max="@line.Product.CountInStore" value="@line.Quantity"
               onchange="changeQnt(@line.Product.ProductId)"/>
        <br />
        <button onclick="deleteLineHandler(@line.Product.ProductId)" class="btn-sm btn-danger">Удалить</button>
    </div>
}